export const SET_LOADING = '@characters/SET_LOADING'
export const SET_LIST = '@characters/SET_LIST'
export const SET_CHARACTER = '@characters/SET_CHARACTER'
export const SET_COMIC = '@characters/SET_COMIC'
export const SET_PAGE = '@characters/SET_PAGE'
export const SET_TOTAL = '@characters/SET_TOTAL'
